### ISSUE TITLE
Configure Codecov to require 90% coverage.

### ISSUE THREAD

**Issue by ndouglas** [ndouglas/mistwood#88]
### User Story

As an engineer, I want Codecov to stop complaining because I went from 94.83% to 94.54% coverage with a PR because ain't nobody got time for that.

### Tasks

- [ ] Add a `codecov.yml` file in the root of the repository with this content:
```yaml
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
```

### Acceptance Criteria

- [ ] Codecov accepts my deviancy.
